routes/web.php
<?php

use App\Http\Controllers\CityController;
use App\Http\Controllers\ClinicController;
use App\Http\Controllers\DetailsController;
use App\Http\Controllers\DoctorController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\EquipmentsController;
use App\Http\Controllers\FeesController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PatientsController;
use App\Http\Controllers\RecepionAuthController;
use App\Http\Controllers\ReceptionController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\roomsController;
use App\Http\Controllers\SpecalitiesController;
use App\Http\Controllers\TreatmentsController;
use App\Http\Controllers\UserAuthController;
// use App\Http\Controllers\roomsController;
// use App\Http\Controllers\HomeController;


use App\Models\employee;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('cms.parent');
// });

Route::prefix('cms/')->middleware('guest:reception')->group(function(){
    Route::get('{guard}/login' , [UserAuthController::class , 'showLogin'])->name('login.view');
    Route::post('{guard}/login' , [UserAuthController::class , 'login']);
});

// Route::prefix('cms')->middleware('auth:admin')->group(function(){
//     Route::get('/logout' , [UserAuthController::class , 'logout'])->name('cms.admin.logout');
// });

// middleware('auth:reception')->
Route::prefix('cms')->group(function(){
    Route::resource('doctor' , DoctorController::class);
    // Route::post('/update-doctor/{id}' , DoctorController::class ,'update')->name('update-doctor');
    Route::post('/update-doctor/{id}' , [DoctorController::class  , 'update'])->name('update-doctor');

    // Route::post('/update-doctor/{id}', 'DoctorController@update')->name('update-doctor');
    Route::resource('patient' , PatientsController::class);
    Route::resource('employee' , EmployeeController::class);
    Route::post('/update-employee/{id}' , [EmployeeController::class  , 'update'])->name('update-employee');

    Route::resource('room',RoomController::class);
    Route::resource('fees' ,FeesController::class);
    Route::resource('clinics' ,ClinicController::class);
    Route::resource('cities' ,CityController::class);
    Route::resource('recepion' ,ReceptionController::class);
    Route::resource('details' ,DetailsController::class);
    Route::resource('treatments' ,TreatmentsController::class);
    Route::resource('spec' ,SpecalitiesController::class);
    Route::resource('equ' ,EquipmentsController::class);

});

Route::prefix('website')->group(function(){

Route::resource('home',HomeController::class);
});

app/Models/details.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class details extends Model
{
    use HasFactory;

    public function Patients()
    {
        return $this->belongsTo(Patients::class);
    }

   
}

app/Http/Controllers/DetailsController.php
<?php


namespace App\Http\Controllers;
use App\Models\details;
use App\Http\Requests\StoredetailsRequest;
use App\Http\Requests\UpdatedetailsRequest;
use  Illuminate\Http\Request;

class DetailsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $details = details::orderBy('id' , 'desc')->get();
        return response()->view('cms.Details.index' , compact('details'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return response()->view('cms.Details.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $validator = Validator($request->all(), [
            'status'=>"required",
            'description'=>"required|min:3|max:25",
        ]);

        if (!$validator->fails()) {
            $details =new details();
            $details->status = $request->get('status');
            $details->description = $request->get('description');

            $isSaved = $details->save();

            return response()->json(['icon' => 'success', 'title' => 'saved is Successfully'], $isSaved ? 201 : 400);
        } else {

            return response()->json(['icon' => 'error', 'title' => $validator->getMessageBag()->first()], 400);
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $details = details::findOrFail($id);
        return response()->view('cms.Details.edit' , compact('details'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator($request->all(), [
            'status'=>"required|min:3|max:25",
            'description'=>"required|min:3|max:25",


        ]);

        if (!$validator->fails()) {
            $details =details::findOrFail();
            $details->status = $request->get('status');
            $details->description = $request->get('description');
            $isSaved = $details->save();
            return response()->json(['icon' => 'success', 'title' => 'update is Successfully'], $isSaved ? 201 : 400);
        } else {

            return response()->json(['icon' => 'error', 'title' => $validator->getMessageBag()->first()], 400);
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $details = details::destroy($id);
        return response()->json(['message' => $details ? "Deleted Successfully" : "Delete Failed"] , $details ? 200 :400);
    }
}

resources/views/cms/details/create.blade.php
@extends('cms.parent')

@section('title' , 'Details')

@section('main-title' , 'Create Details')

@section('small-title' , 'Details')

@section('styles')
{{-- <link rel="stylesheet" href="{{ asset('cms/bootstrap-datepicker/css/bootstrap-datepicker.min.css') }}"> --}}

@endsection

@section('content')
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Create Details</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form id="create_form">
                        @csrf
                        <div class="card-body">



                            <div class="row">

                            <div class="form-group col-md-4">
                                <label for="description"> description</label>
                                <input type="text" class="form-control" name="description" id="description"
                                    placeholder="Enter your  description">
                            </div>

                            <div class="form-group col-md-4">
                                <label for="status">Status</label>

                                <select class="form-select form-select-sm" name="status" style="width: 100%;"
                                    id="status" aria-label=".form-select-sm example">
                                    <option selected></option>
                                    <option value="Active">Active</option>
                                    <option value="InActive">InActive</option>
                                </select>
                            </div>

                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                    <button type="button" onclick="performStore()" class="btn btn-primary">Store</button>
                    <a href="{{ route('details.index') }}" type="button"  class="btn btn-success">Return Back</a>

                </div>
                </form>
            </div>



</section>
@endsection
{{-- <script src="{{ asset('cms/bootstrap-datepicker/js/bootstrap-datepicker.min.js') }}"></script> --}}

@section('scripts')

    <script>
        function performStore(){
            let data ={
                description: document.getElementById('description').value,
                status: document.getElementById('status').value,
            }
            store('/cms/details',data);
        }
    </script>

@endsection

resources/views/cms/details/edit.blade.php
@extends('cms.parent')

@section('title' , 'Details')

@section('main-title' , 'Edit Details')

@section('small-title' , 'Details')

@section('styles')

@endsection

@section('content')
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Edit Details</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form id="create_form">
                        @csrf
                        <div class="card-body">
                            <div class="row">

                            <div class="form-group col-md-4">
                                <label for="description">description</label>
                                <input type="text" class="form-control" name="description" id="description"
                                    value="{{ $details->description }}" placeholder="Enter your  description">
                            </div>
                            <div class="form-group col-md-4">
                                <label for="status">Status</label>

                                <select class="form-select form-select-sm" name="status" style="width: 100%;"
                                    id="status" aria-label=".form-select-sm example">
                                    <option selected>{{ $details->status }}</option>
                                    <option value="Active">Active</option>
                                    <option value="InActive">InActive</option>
                                </select>
                            </div>


                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Update</button>
                </div>
                </form>
            </div>



</section>
@endsection

@section('scripts')

<script>
    function performUpdate(id){
        let data ={
            description: document.getElementById('description').value,
            status: document.getElementById('status').value,

        }
        let redirectUlr = '/cms/details'
        update('/cms/details/'+ id, data , redirectUlr);

    }

</script>
@endsection

resources/views/cms/details/index.blade.php
@extends('cms.parent')

@section('title' , 'details')

@section('main-title' , 'Index details')

@section('small-title' , 'details')

@section('styles')

@endsection

@section('content')
<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header ">
          <h3 class="card-title"></h3>
                <a href="{{ route('details.create') }}" type="button"  class="btn btn-success">Add new details</a>

          <div class="card-tools">
            <div class="input-group input-group-sm" style="width: 150px;">
              <input type="text" description="table_search" class="form-control float-right" placeholder="Search">

              <div class="input-group-append">
                <button type="submit" class="btn btn-default">
                  <i class="fas fa-search"></i>
                </button>
              </div>
            </div>
          </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body table-responsive p-0">
          <table class="table  table-bordered table-striped table-hover text-nowrap">
            <thead>
              <tr>
                <th>ID</th>
                <th> description</th>
                <th> status</th>
                <th>Created At</th>
                <th>Setting</th>

              </tr>
            </thead>
            <tbody>
                {{-- <td><span class="tag tag-success">Approved</span></td> --}}
                @foreach ($details as $detail )
                <tr>
                    <td>{{ $detail->id }}</td>
                    <td>{{ $detail->description }}</td>
                    <td>{{ $detail->status }}</td>
                    <td>{{ $detail->created_at }}</td>
                    <td>
                        <div class="btn-group">
                            <a href="{{ route('details.edit', $detail->id) }}" class="btn btn-info">
                              <i class="fas fa-edit"></i>
                            </a>


                        <a href="#" onclick="performDestroy({{ $detail->id }}, this)" class="btn btn-danger">
                            <i class="fas fa-trash-alt"></i>
                        </a>

                        </div>
                    </td>
                  </tr>
                @endforeach


            </tbody>
          </table>
        </div>
    </div>
</div>

      </div>
    </div>

    </div>
  </div>
@endsection

@section('scripts')

<script>
    function performDestroy(id , ref){
        confirmDestroy('/cms/details/'+id ,ref);
    }
</script>
@endsection