routes/web.php
<?php

use App\Http\Controllers\CityController;
use App\Http\Controllers\ClinicController;
use App\Http\Controllers\DetailsController;
use App\Http\Controllers\DoctorController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\EquipmentsController;
use App\Http\Controllers\FeesController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PatientsController;
use App\Http\Controllers\RecepionAuthController;
use App\Http\Controllers\ReceptionController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\roomsController;
use App\Http\Controllers\SpecalitiesController;
use App\Http\Controllers\TreatmentsController;
use App\Http\Controllers\UserAuthController;
// use App\Http\Controllers\roomsController;
// use App\Http\Controllers\HomeController;


use App\Models\employee;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('cms.parent');
// });

Route::prefix('cms/')->middleware('guest:reception')->group(function(){
    Route::get('{guard}/login' , [UserAuthController::class , 'showLogin'])->name('login.view');
    Route::post('{guard}/login' , [UserAuthController::class , 'login']);
});

// Route::prefix('cms')->middleware('auth:admin')->group(function(){
//     Route::get('/logout' , [UserAuthController::class , 'logout'])->name('cms.admin.logout');
// });

// middleware('auth:reception')->
Route::prefix('cms')->group(function(){
    Route::resource('doctor' , DoctorController::class);
    // Route::post('/update-doctor/{id}' , DoctorController::class ,'update')->name('update-doctor');
    Route::post('/update-doctor/{id}' , [DoctorController::class  , 'update'])->name('update-doctor');

    // Route::post('/update-doctor/{id}', 'DoctorController@update')->name('update-doctor');
    Route::resource('patient' , PatientsController::class);
    Route::resource('employee' , EmployeeController::class);
    Route::post('/update-employee/{id}' , [EmployeeController::class  , 'update'])->name('update-employee');

    Route::resource('room',RoomController::class);
    Route::resource('fees' ,FeesController::class);
    Route::resource('clinics' ,ClinicController::class);
    Route::resource('cities' ,CityController::class);
    Route::resource('recepion' ,ReceptionController::class);
    Route::resource('details' ,DetailsController::class);
    Route::resource('treatments' ,TreatmentsController::class);
    Route::resource('spec' ,SpecalitiesController::class);
    Route::resource('equ' ,EquipmentsController::class);

});

Route::prefix('website')->group(function(){

Route::resource('home',HomeController::class);
});

app/Models/clinic.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class clinic extends Model
{
    use HasFactory;
    public function patients()
    {
        return $this->hasMany(patients::class);
    }

    public function rooms()
    {
        return $this->hasMany(rooms::class);
    }

    public function doctors()
    {
        return $this->hasMany(doctor::class);
    }

    public function equipments()
    {
        return $this->hasMany(equipments::class);
    }

    public function reception()
    {
        return $this->hasOne(reception::class);
    }

    public function city()
    {
        return $this->belongsTo(city::class);
    }

    public function employees()
    {
        return $this->hasMany(employee::class);
    }
    
}

app/Http/Controllers/ClinicController.php
<?php

namespace App\Http\Controllers;

use App\Models\clinic;
use App\Http\Requests\StoreclinicRequest;
use App\Http\Requests\UpdateclinicRequest;
use App\Models\city;
use App\Models\reception;
// use Illuminate\Http\Client\Request;
use App\Schedules;
use  Illuminate\Http\Request;

class ClinicController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clinics = Clinic::orderBy('id' , 'desc')->get();
        return response()->view('cms.Clinic.index' , compact('clinics'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $cities= city::with('clinic')->get();
        $receptions= reception::with('clinic')->get();
        return response()->view('cms.Clinic.create',compact('cities','receptions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $validator = Validator($request->all(), [
            'name'=>"required|min:3|max:25",
            'phone'=>"required|min:3|max:25",
        ]);

        if (!$validator->fails()) {
            $clinics =new Clinic();
            $clinics->name = $request->get('name');
            $clinics->phone = $request->get('phone');

            $isSaved = $clinics->save();

            return response()->json(['icon' => 'success', 'title' => 'saved is Successfully'], $isSaved ? 201 : 400);
        } else {

            return response()->json(['icon' => 'error', 'title' => $validator->getMessageBag()->first()], 400);
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $clinics = Clinic::findOrFail($id);
        return response()->view('cms.Clinic.edit' , compact('clinics'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator($request->all(), [
            'name'=>"required|min:3|max:25",
            'phone'=>"required|min:3|max:25",


        ]);
        if(!$validator->fails()){
            $clinics = clinic::findOrFail($id);
                $clinics->name = $request->get('name');
                $clinics->phone = $request->get('phone');
                // $clinics->reception_id = $request->get('reception_id');


            $isSaved = $clinics->save();
            return response()->json(['icon' => 'success', 'title' => 'update is Successfully'], $isSaved ? 201 : 400);
        } else {

            return response()->json(['icon' => 'error', 'title' => $validator->getMessageBag()->first()], 400);
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $clinics = Clinic::destroy($id);
        return response()->json(['message' => $clinics ? "Deleted Successfully" : "Delete Failed"] , $clinics ? 200 :400);
    }
}

resources/views/cms/Clinic/create.blade.php
@extends('cms.parent')

@section('title' , 'Clinic')

@section('main-title' , 'Create Clinic')

@section('small-title' , 'Clinics')

@section('styles')
<link rel="stylesheet" href="{{ asset('cms/bootstrap-datepicker/css/bootstrap-datepicker.min.css') }}">

@endsection

@section('content')
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Create Clinic</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form id="create_form">
                        @csrf
                        <div class="card-body">
                            <div class="row">
                             <div class="col-md-6">
                                    <div class="form-group">
                                      <label>City</label>
                                      <select class="form-control select2" name="city_id" style="width: 100%;" id="city_id">
                                        @foreach ($cities as $city)
                                        <option value="{{ $city->id }}">{{ $city->name }}</option>
                                        @endforeach
                                      </select>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                      <label>Reception</label>
                                      <select class="form-control select2" name="reception_id" style="width: 100%;" id="reception_id">
                                        @foreach ($receptions as $reception)
                                        <option value="{{ $reception->id }}">{{ $reception->name }}</option>
                                        @endforeach
                                      </select>
                                    </div>
                                </div>

                              </div>

                            <div class="row">

                            <div class="form-group col-md-4">
                                <label for="name"> name</label>
                                <input type="text" class="form-control" name="name" id="name"
                                    placeholder="Enter your  name">
                            </div>

                            <div class="form-group col-md-4">
                                <label for="phone">phone</label>
                                <input type="text" class="form-control" name="phone" id="phone"
                                    placeholder="Enter youe phone number ">
                            </div>

                </div>
                        </div>
                <!-- /.card-body -->

                <div class="card-footer">
                    <button type="button" onclick="performStore()" class="btn btn-primary">Store</button>
                    <a href="{{ route('clinics.index') }}" type="button"  class="btn btn-success">Return Back</a>

                </div>
                </form>
            </div>



</section>
@endsection
{{-- <script src="{{ asset('cms/bootstrap-datepicker/js/bootstrap-datepicker.min.js') }}"></script> --}}

@section('scripts')

    <script>
        function performStore(){
            let data ={
                name: document.getElementById('name').value,
                phone: document.getElementById('phone').value,
            }
            store('/cms/clinics',data);
        }
    </script>

@endsection

resources/views/cms/Clinic/edit.blade.php
@extends('cms.parent')

@section('title' , 'Clinic')

@section('main-title' , 'Edit Clinic')

@section('small-title' , 'Clinics')

@section('styles')

@endsection

@section('content')
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Edit Clinic</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form id="create_form">
                        @csrf
                        <div class="card-body">
                            <div class="row">

                            <div class="form-group col-md-4">
                                <label for="name">name</label>
                                <input type="text" class="form-control" name="name" id="name"
                                    value="{{ $clinics->name }}" placeholder="Enter your  name">
                            </div>
                            <div class="form-group col-md-4">
                                <label for="phone">phone</label>
                                <input type="text" class="form-control" name="phone" id="phone"
                                value="{{ $clinics->phone }}" placeholder="Enter your phone ">
                            </div>


                </div>
                <!-- /.card-body -->

                    <div class="card-footer">

                    <button type="button" onclick="performUpdate({{ $clinics->id }})" class="btn btn-primary">Update</button>
                    <a href="{{ route('doctor.index') }}" type="button"  class="btn btn-success">Return Back</a>

                </div>
                </form>
            </div>



</section>
@endsection

@section('scripts')

<script>
    function performUpdate(id){
        let data ={
            name: document.getElementById('name').value,
            phone: document.getElementById('phone').value,

        }
        let redirectUlr = '/cms/clinics'
        update('/cms/clinics/'+ id, data , redirectUlr);

    }

</script>
@endsection

resources/views/cms/Clinic/index.blade.php
@extends('cms.parent')

@section('title' , 'Clinic')

@section('main-title' , 'Index Clinic')

@section('small-title' , 'clinic')

@section('styles')

@endsection

@section('content')
<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header ">
          <h3 class="card-title"></h3>
                <a href="{{ route('clinics.create') }}" type="button"  class="btn btn-success">Add new clinic</a>

          <div class="card-tools">
            <div class="input-group input-group-sm" style="width: 150px;">
              <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

              <div class="input-group-append">
                <button type="submit" class="btn btn-default">
                  <i class="fas fa-search"></i>
                </button>
              </div>
            </div>
          </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body table-responsive p-0">
          <table class="table  table-bordered table-striped table-hover text-nowrap">
            <thead>
              <tr>
                <th>ID</th>
                <th> name</th>
                <th> phone</th>
                <th>Created At</th>
                <th>Setting</th>

              </tr>
            </thead>
            <tbody>
                {{-- <td><span class="tag tag-success">Approved</span></td> --}}
                @foreach ($clinics as $clinic )
                <tr>
                    <td>{{ $clinic->id }}</td>
                    <td>{{ $clinic->name }}</td>
                    <td>{{ $clinic->phone }}</td>
                    <td>{{ $clinic->created_at }}</td>
                    <td>
                        <div class="btn-group">
                            <a href="{{ route('clinics.edit', $clinic->id) }}" class="btn btn-info">
                              <i class="fas fa-edit"></i>
                            </a>


                        <a href="#" onclick="performDestroy({{ $clinic->id }}, this)" class="btn btn-danger">
                            <i class="fas fa-trash-alt"></i>
                        </a>

                        </div>
                    </td>
                  </tr>
                @endforeach


            </tbody>
          </table>
        </div>
    </div>
</div>

      </div>
    </div>

    </div>
  </div>
@endsection

@section('scripts')

<script>
    function performDestroy(id , ref){
    confirmDestroy('/cms/clinics/'+id ,ref);
    }
</script>
@endsection