routes/web.php
<?php

use App\Http\Controllers\CityController;
use App\Http\Controllers\ClinicController;
use App\Http\Controllers\DetailsController;
use App\Http\Controllers\DoctorController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\EquipmentsController;
use App\Http\Controllers\FeesController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PatientsController;
use App\Http\Controllers\RecepionAuthController;
use App\Http\Controllers\ReceptionController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\roomsController;
use App\Http\Controllers\SpecalitiesController;
use App\Http\Controllers\TreatmentsController;
use App\Http\Controllers\UserAuthController;
// use App\Http\Controllers\roomsController;
// use App\Http\Controllers\HomeController;


use App\Models\employee;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('cms.parent');
// });

Route::prefix('cms/')->middleware('guest:reception')->group(function(){
    Route::get('{guard}/login' , [UserAuthController::class , 'showLogin'])->name('login.view');
    Route::post('{guard}/login' , [UserAuthController::class , 'login']);
});

// Route::prefix('cms')->middleware('auth:admin')->group(function(){
//     Route::get('/logout' , [UserAuthController::class , 'logout'])->name('cms.admin.logout');
// });

// middleware('auth:reception')->
Route::prefix('cms')->group(function(){
    Route::resource('doctor' , DoctorController::class);
    // Route::post('/update-doctor/{id}' , DoctorController::class ,'update')->name('update-doctor');
    Route::post('/update-doctor/{id}' , [DoctorController::class  , 'update'])->name('update-doctor');

    // Route::post('/update-doctor/{id}', 'DoctorController@update')->name('update-doctor');
    Route::resource('patient' , PatientsController::class);
    Route::resource('employee' , EmployeeController::class);
    Route::post('/update-employee/{id}' , [EmployeeController::class  , 'update'])->name('update-employee');

    Route::resource('room',RoomController::class);
    Route::resource('fees' ,FeesController::class);
    Route::resource('clinics' ,ClinicController::class);
    Route::resource('cities' ,CityController::class);
    Route::resource('recepion' ,ReceptionController::class);
    Route::resource('details' ,DetailsController::class);
    Route::resource('treatments' ,TreatmentsController::class);
    Route::resource('spec' ,SpecalitiesController::class);
    Route::resource('equ' ,EquipmentsController::class);

});

Route::prefix('website')->group(function(){

Route::resource('home',HomeController::class);
});

resources/views/cms/spaecality/create.blade.php
@extends('cms.parent')

@section('title' , 'Specality')

@section('main-title' , 'Create Specality')

@section('small-title' , 'Specality')

@section('styles')
<link rel="stylesheet" href="{{ asset('cms/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
@endsection

@section('content')
<div class="row">

    <div class="col-md-12">
      <!-- general form elements -->
      <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">Quick Example</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form action="{{ route('spec.store')}}" method="POST">
            @csrf
          <div class="card-body">
            <div class="col-md-9">
                <div class="form-group">
                  <label>clinic</label>
                  <select class="form-control select2" name="clinic_id" style="width: 100%;" id="clinic_id">
                    @foreach ($clinic as $clinics)
                    <option value="{{ $clinics->id }}">{{ $clinics->name}}</option>
                    @endforeach
                  </select>
                </div>
            </div>
            <div class="form-group">
              <label for="name">name</label>
              <input type="text" class="form-control" id="name" name="name" placeholder="Enter name">
            </div>
            <div class="form-group">
              <label for="des">description</label>
              <input type="text" class="form-control" id="des" name="description" placeholder="Enter description">
            </div>

          <!-- /.card-body -->

              <div class="card-footer">
                <button type="submit" class="btn btn-info">Store</button>
             </div>


          <!-- /.card-footer -->
        </form>
      </div>
      <!-- /.card -->
@endsection

@section('scripts')
<script src="{{ asset('cms/plugins/select2/js/select2.full.min.js') }}"></script>
@endsection

resources/views/cms/spaecality/edit.blade.php
@extends('cms.parent')

@section('title' , 'Specality')

@section('main-title' , 'Edit Specality')

@section('small-title' , 'Specality')

@section('styles')

@endsection

@section('content')
<div class="row">
    <div class="col-md-12">
      <!-- general form elements -->
      <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">Quick Example</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form action="{{ route('spec.store')}}" method="POST">
            @csrf
          <div class="card-body">
            <div class="col-md-9">
                <div class="form-group">
                  <label>clinic</label>
                  <select class="form-control select2" name="clinic_id" style="width: 100%;" id="clinic_id">
                    @foreach ($clinic as $clinics)
                    <option value="{{ $clinics->id }}">{{ $clinics->name}}</option>
                    @endforeach
                  </select>
                </div>
            </div>
            <div class="form-group">
              <label for="name">name</label>
              <input type="text" class="form-control" id="name" name="name" value="{{ $specality->name }}" placeholder="Enter name">
            </div>
            <div class="form-group">
              <label for="des">description</label>
              <input type="text" class="form-control" id="des" name="description" value="{{ $specality->description }}" placeholder="Enter description">
            </div>

          <!-- /.card-body -->

              <div class="card-footer">
                <button type="submit" class="btn btn-info">Update</button>
             </div>


          <!-- /.card-footer -->
        </form>
      </div>
      <!-- /.card -->
@endsection

@section('scripts')

@endsection

resources/views/cms/spaecality/index.blade.php
@extends('cms.parent')

@section('title' , 'Specality')

@section('main-title' , 'Index Specality')

@section('small-title' , ' Specality')

@section('styles')

@endsection

@section('content')
<!-- /.row -->
<div class="row">
  <div class="col-12">
    <div class="card table table-bordered">
      <div class="card-header">
        <h3 class="card-title">index Specality</h3>

        <div class="card-tools">
          <div class="input-group input-group-sm" style="width: 150px;">
            <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

            <div class="input-group-append">
              <button type="submit" class="btn btn-default">
                <i class="fas fa-search"></i>
              </button>
            </div>
          </div>
        </div>
      </div>
      <!-- /.card-header -->
      <div class="card-body table-responsive p-0" style="height: 300px;">
        <table class="table table-head-fixed text-nowrap">
          <thead>
            <tr>
              <th>ID</th>
              <th>name</th>
              <th>description</th>
              <th>created_at</th>
              <th>updated_at</th>
              <th>setting</th>
            </tr>
          </thead>
          <tbody>
              @foreach ($specality as $specalities )
                <tr>
                  <td>{{ $specalities->id }}</td>
                  <td>{{ $specalities->name }}</td>
                  <td>{{ $specalities->description}}</td>
                  <td>{{ $specalities->created_at }}</td>
                  <td>{{ $specalities->updated_at}}</td>
                  <td>
                    <div class="btn-group">
                        <a href="{{ route('spec.edit',$specalities->id)}}" class="btn btn-info">
                          <i class="fas fa-edit"></i>
                        </a>
                        <form action="{{ route('spec.destroy', $specalities->id)}}" method="POST">
                            @csrf
                            @method('DELETE')
                           <button type="submit" class="btn btn-danger">
                             <i class="fas fa-trash-alt"></i>
                           </button>
                        </form>

                   </div>
                  </td>
            </tr>
              @endforeach

          </tbody>
        </table>
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.card -->
  </div>
</div>
<!-- /.row -->

@endsection

@section('scripts')

@endsection