routes/web.php
<?php

use App\Http\Controllers\CityController;
use App\Http\Controllers\ClinicController;
use App\Http\Controllers\DetailsController;
use App\Http\Controllers\DoctorController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\EquipmentsController;
use App\Http\Controllers\FeesController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PatientsController;
use App\Http\Controllers\RecepionAuthController;
use App\Http\Controllers\ReceptionController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\roomsController;
use App\Http\Controllers\SpecalitiesController;
use App\Http\Controllers\TreatmentsController;
use App\Http\Controllers\UserAuthController;
// use App\Http\Controllers\roomsController;
// use App\Http\Controllers\HomeController;


use App\Models\employee;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('cms.parent');
// });

Route::prefix('cms/')->middleware('guest:reception')->group(function(){
    Route::get('{guard}/login' , [UserAuthController::class , 'showLogin'])->name('login.view');
    Route::post('{guard}/login' , [UserAuthController::class , 'login']);
});

// Route::prefix('cms')->middleware('auth:admin')->group(function(){
//     Route::get('/logout' , [UserAuthController::class , 'logout'])->name('cms.admin.logout');
// });

// middleware('auth:reception')->
Route::prefix('cms')->group(function(){
    Route::resource('doctor' , DoctorController::class);
    // Route::post('/update-doctor/{id}' , DoctorController::class ,'update')->name('update-doctor');
    Route::post('/update-doctor/{id}' , [DoctorController::class  , 'update'])->name('update-doctor');

    // Route::post('/update-doctor/{id}', 'DoctorController@update')->name('update-doctor');
    Route::resource('patient' , PatientsController::class);
    Route::resource('employee' , EmployeeController::class);
    Route::post('/update-employee/{id}' , [EmployeeController::class  , 'update'])->name('update-employee');

    Route::resource('room',RoomController::class);
    Route::resource('fees' ,FeesController::class);
    Route::resource('clinics' ,ClinicController::class);
    Route::resource('cities' ,CityController::class);
    Route::resource('recepion' ,ReceptionController::class);
    Route::resource('details' ,DetailsController::class);
    Route::resource('treatments' ,TreatmentsController::class);
    Route::resource('spec' ,SpecalitiesController::class);
    Route::resource('equ' ,EquipmentsController::class);

});

Route::prefix('website')->group(function(){

Route::resource('home',HomeController::class);
});

app/Models/equipments.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class equipments extends Model
{
    use HasFactory;

    public function room()
    {
        return $this->belongsTo(room::class);
    }

    public function clinic()
    {
        return $this->belongsTo(clinic::class);
    }

}

app/Http/Controllers/EquipmentsController.php
<?php

namespace App\Http\Controllers;

use App\Models\equipments;
use App\Http\Requests\StoreequipmentsRequest;
use App\Http\Requests\UpdateequipmentsRequest;
use App\Models\clinic;
use App\Models\room;
// use GuzzleHttp\Psr7\Request;
use Illuminate\Http\Request;


class EquipmentsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $equipments = equipments::all();
        return response()->view('cms.equipments.index',compact('equipments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $room= room::with('equipments')->get();
        $clin=clinic::with('equipments')->get();
        return response()->view('cms.equipments.create',compact('room','clin'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreequipmentsRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $equipments=new equipments();
        $equipments -> room_id= $request->get('room_id');
        $equipments -> clinics_id= $request->get('clinics_id');
        $equipments -> name= $request->get('name');
        $issaved = $equipments->save();
        return redirect()->route('equ.index');
        return response()->json(['message'=>$equipments ?"created successfully" : "Faield Created"],$issaved?200:400);

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\equipments  $equipments
     * @return \Illuminate\Http\Response
     */
    public function show(equipments $equipments)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\equipments  $equipments
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $clin=clinic::with('equipments')->get();
        $room= room::with('equipments')->get();
        $equipments=equipments::findOrFail($id);
        return response()->view('cms.equipments.edit',compact('equipments','room','clin'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateequipmentsRequest  $request
     * @param  \App\Models\equipments  $equipments
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
        $equipments=equipments::findOrFail($id);
        $equipments -> name= $request->get('name');
        $issaved = $equipments->save();
        return redirect()->route('equ.index');
        return response()->json(['message'=>$equipments ?"created successfully" : "Faield Created"],$issaved?200:400);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\equipments  $equipments
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $equipments=equipments::destroy($id);
        return redirect()->back();
    }
}

resources/views/cms/equipments/create.blade.php
@extends('cms.parent')

@section('title' , 'Equipments')

@section('main-title' , 'Create Equipments')

@section('small-title' , 'Equipments')

@section('styles')
<link rel="stylesheet" href="{{ asset('cms/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
@endsection

@section('content')
<div class="row">
    <!-- left column -->
    <div class="col-md-12">
      <!-- general form elements -->
      <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">Create Equipments</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form action="{{ route('equ.store')}}" method="POST">
            @csrf
          <div class="card-body">
            <div class="row">
                <div class="col-md-9">
                    <div class="form-group">
                      <label>room</label>
                      <select class="form-control select2" name="room_id" style="width: 100%;" id="room_id">
                        @foreach ($room as $rooms)
                        <option value="{{ $rooms->id }}"></option>
                        @endforeach
                      </select>
                    </div>
                </div>
                <div class="col-md-9">
                    <div class="form-group">
                      <label>clinic</label>
                      <select class="form-control select2" name="clinic_id" style="width: 100%;" id="clinic_id">
                        @foreach ($clin as $clinics)
                        <option value="{{ $clinics->id }}">{{ $clinics->name}}</option>
                        @endforeach
                      </select>
                    </div>
                </div>

            </div>
            <div class="form-group">
              <label for="name">Name</label>
              <input type="text" class="form-control" name="name" id="name" placeholder="Enter name">
            </div>
            <div class="form-group">
              <label for="phone">Phone</label>
              <input type="text" class="form-control" name="phone" id="phone" placeholder="Enter phone">
            </div>
            <div class="form-group">
                <label for="email">Email</label>
                <input type="text" class="form-control" name="email" id="email" placeholder="Enter email">
              </div>
              <div class="form-group">
                <label for="date">Date_Of_Booking</label>
                <input id="date" type="date"  name="date_of_booking" class="form-control"
                    placeholder="date of booking">
            </div>
          </div>
          <!-- /.card-body -->

          <div class="card-footer">
            <button type="submit" class="btn btn-primary">Store</button>
            <a href="{{ route('equ.index')}}" type="button"  class="btn btn-primary">Return Back</a>

        </div>
        </form>
      </div>
      <!-- /.card -->


@endsection

@section('scripts')
<script src="{{ asset('cms/plugins/select2/js/select2.full.min.js') }}"></script>

@endsection

resources/views/cms/equipments/edit.blade.php
@extends('cms.parent')

@section('title' , 'Equipments')

@section('main-title' , 'Edit Equipments')

@section('small-title' , 'Equipments')

@section('styles')

@endsection

@section('content')
<div class="row">
    <!-- left column -->
    <div class="col-md-12">
      <!-- general form elements -->
      <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">Quick Example</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form action="{{ route('equ.store')}}" method="POST">
            @csrf
          <div class="card-body">
            <div class="row">
                <div class="col-md-9">
                    <div class="form-group">
                      <label>room</label>
                      <select class="form-control select2" name="room_id" style="width: 100%;" id="room_id">
                        @foreach ($room as $rooms)
                        <option value="{{ $rooms->id }}"></option>
                        @endforeach
                      </select>
                    </div>
                </div>
                <div class="col-md-9">
                    <div class="form-group">
                      <label>clinic</label>
                      <select class="form-control select2" name="clinic_id" style="width: 100%;" id="clinic_id">
                        @foreach ($clin as $clinics)
                        <option value="{{ $clinics->id }}">{{ $clinics->name}}</option>
                        @endforeach
                      </select>
                    </div>
                </div>

            </div>
            <div class="form-group">
              <label for="name">Name</label>
              <input type="text" class="form-control" id="name" name="name" value={{ $equipments->name }} placeholder="Enter name">
            </div>
            <div class="form-group">
              <label for="phone">Phone</label>
              <input type="text" class="form-control" id="phone" name="phone" value={{ $equipments->phone }} placeholder="Enter phone">
            </div>
            <div class="form-group">
                <label for="email">Email</label>
                <input type="text" class="form-control" id="email" name="email" value={{ $equipments->email }} placeholder="Enter email">
              </div>
              <div class="form-group">
                <label for="booking">Date_Of_Booking</label>
                <input type="text" class="form-control" id="booking" name="date_of_booking" value={{ $equipments->date_of_booking }} placeholder="Enter date_of_booking">
              </div>


          </div>
          <!-- /.card-body -->

          <div class="card-footer">
            <button type="submit" class="btn btn-primary">Update</button>
          </div>
        </form>
      </div>
      <!-- /.card -->


@endsection

@section('scripts')

@endsection

resources/views/cms/equipments/index.blade.php
@extends('cms.parent')

@section('title' , 'Equipments')

@section('main-title' , 'Index Equipments')

@section('small-title' , 'Equipments')

@section('styles')

@endsection

@section('content')
<!-- /.row -->
<div class="row">
  <div class="col-12">
    <div class="card table table-bordered">
      <div class="card-header">
        <h3 class="card-title">Index Equipments</h3>

        <div class="card-tools">
          <div class="input-group input-group-sm" style="width: 150px;">
            <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

            <div class="input-group-append">
              <button type="submit" class="btn btn-default">
                <i class="fas fa-search"></i>
              </button>
            </div>
          </div>
        </div>
      </div>
      <!-- /.card-header -->
      <div class="card-body table-responsive p-0">
        <table class="table table-hover text-nowrap">
          <thead>
            <tr>
              <th>ID</th>
              <th>name</th>
              <th>created_at</th>
              <th>updated_at</th>
              <th>setting</th>
            </tr>
          </thead>
          <tbody>
              @foreach ($equipments as $equipment )
                <tr>
                  <td>{{ $equipment->id }}</td>
                  <td>{{ $equipment->name }}</td>
                  <td>{{ $equipment->created_at }}</td>
                  <td>{{ $equipment->updated_at }}</td>
                  <td>
                    <div class="btn-group">
                        <a href="{{ route('equ.edit', $equipment->id) }}" class="btn btn-info">
                          <i class="fas fa-edit"></i>
                        </a>
                        <form action="{{ route('equ.destroy' , $equipment->id) }}" method="POST">
                            @csrf
                            @method('DELETE')
                          <button type="submit" class="btn btn-danger">
                           <i class="fas fa-trash-alt"></i>
                          </button>
                        </form>

                   </div>
                  </td>
                 {{--  <td>Bacon ipsum dolor sit amet salami venison chicken flank fatback doner.</td>  --}}
               </tr>
              @endforeach

          </tbody>
        </table>
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.card -->
  </div>
</div>
<!-- /.row -->
@endsection

@section('scripts')

@endsection